import { LiveMeStreamer, LiveMeGiftItem, RechargeTier } from './types';

// Zero fake/mock streamers: only real, active broadcasting users are shown
export const LIVEME_STREAMERS: LiveMeStreamer[] = [];

export const LIVEME_GIFTS: LiveMeGiftItem[] = [
  // Category: Popular (Featuring our 4 Real High-Fidelity Project Gifts at the very top + LiveMe 4x4 Grid)
  {
    id: 'rose',
    name: 'Rose',
    coins: 1,
    icon: '🌹',
    imageIcon: './gifts/rose/icon.webp',
    soundUrl: './gifts/rose/sound.mp3',
    category: 'popular',
    isAnimation: true,
    animationKey: 'rose',
  },
  {
    id: 'tropical-mosquito',
    name: 'Tropical Mosquito',
    coins: 69,
    icon: '🦟',
    imageIcon: './gifts/tropical-mosquito/icon.webp',
    soundUrl: './gifts/tropical-mosquito/sound.mp3',
    category: 'popular',
    isAnimation: true,
    animationKey: 'tropical-mosquito',
  },
  {
    id: 'dragon',
    name: 'Dragon',
    coins: 1314,
    icon: '🐉',
    imageIcon: './gifts/dragon/icon.webp',
    soundUrl: './gifts/dragon/sound.mp3',
    category: 'popular',
    isAnimation: true,
    animationKey: 'dragon',
  },
  {
    id: 'super-galaxy',
    name: 'Super Galaxy',
    coins: 3000,
    icon: '🌌',
    imageIcon: './gifts/super-galaxy/icon.webp',
    soundUrl: './gifts/super-galaxy/sound.mp3',
    category: 'popular',
    isAnimation: true,
    animationKey: 'super-galaxy',
  },
  { id: 'crown-heart', name: 'Crown Heart', coins: 1, icon: '👑❤️', category: 'popular' },
  { id: 'bouquet', name: 'Bouquet', coins: 1, icon: '💐', category: 'popular' },
  { id: 'lightning', name: 'Lightning', coins: 1, icon: '⚡', category: 'popular' },
  { id: 'thumbs-up', name: 'Thumbs Up', coins: 1, icon: '👍', category: 'popular' },
  { id: 'cute-heart', name: 'Cute Heart', coins: 5, icon: '🥰', category: 'popular' },
  { id: 'high-heels', name: 'High Heels', coins: 5, icon: '👠', category: 'popular' },
  { id: 'taxi', name: 'Yellow Taxi', coins: 5, icon: '🚕', category: 'popular' },
  { id: 'red-lips', name: 'Red Lips', coins: 30, icon: '💋', category: 'popular' },
  { id: 'rainbow', name: 'Rainbow', coins: 30, icon: '🌈', category: 'popular' },
  { id: 'feather-duster', name: 'Feather Duster', coins: 69, icon: '🪶', category: 'popular' },
  { id: 'cocktail', name: 'Cocktail', coins: 99, icon: '🍹', category: 'popular' },
  { id: 'diamond-ring', name: 'Diamond Ring', coins: 520, icon: '💍', category: 'popular' },

  // Category: Special (Signature High-Tier Animations & Real Project Gifts)
  {
    id: 'dragon-special',
    name: 'Dragon',
    coins: 1314,
    icon: '🐉',
    imageIcon: './gifts/dragon/icon.webp',
    soundUrl: './gifts/dragon/sound.mp3',
    category: 'special',
    isAnimation: true,
    animationKey: 'dragon',
  },
  {
    id: 'galaxy-special',
    name: 'Super Galaxy',
    coins: 3000,
    icon: '🌌',
    imageIcon: './gifts/super-galaxy/icon.webp',
    soundUrl: './gifts/super-galaxy/sound.mp3',
    category: 'special',
    isAnimation: true,
    animationKey: 'super-galaxy',
  },
  {
    id: 'mosquito-special',
    name: 'Tropical Mosquito',
    coins: 250,
    icon: '🦟',
    imageIcon: './gifts/tropical-mosquito/icon.webp',
    soundUrl: './gifts/tropical-mosquito/sound.mp3',
    category: 'special',
    isAnimation: true,
    animationKey: 'tropical-mosquito',
  },
  {
    id: 'rose-special',
    name: 'Crystal Rose',
    coins: 10,
    icon: '🌹',
    imageIcon: './gifts/rose/icon.webp',
    soundUrl: './gifts/rose/sound.mp3',
    category: 'special',
    isAnimation: true,
    animationKey: 'rose',
  },
  { id: 'fireworks', name: 'Fireworks', coins: 299, icon: '🎆', category: 'special' },
  { id: 'luxury-yacht', name: 'Luxury Yacht', coins: 1999, icon: '🛥️', category: 'special' },
  { id: 'private-jet', name: 'Private Jet', coins: 4999, icon: '✈️', category: 'special' },
  { id: 'fairy-castle', name: 'Fairy Castle', coins: 9999, icon: '🏰', category: 'special' },
  { id: 'phoenix', name: 'Golden Phoenix', coins: 5200, icon: '🦅', category: 'special' },

  // Category: Pranks
  { id: 'prank-duster', name: 'Feather Tickle', coins: 69, icon: '🪶', category: 'pranks' },
  { id: 'prank-tomato', name: 'Rotten Tomato', coins: 10, icon: '🍅', category: 'pranks' },
  { id: 'prank-water', name: 'Water Splash', coins: 25, icon: '💦', category: 'pranks' },
  { id: 'prank-bomb', name: 'Stink Bomb', coins: 50, icon: '💣', category: 'pranks' },
  { id: 'prank-ghost', name: 'Ghost Pop', coins: 99, icon: '👻', category: 'pranks' },
  { id: 'prank-bucket', name: 'Ice Bucket', coins: 150, icon: '🪣', category: 'pranks' },
  { id: 'prank-pie', name: 'Cream Pie', coins: 88, icon: '🥧', category: 'pranks' },
  { id: 'prank-slime', name: 'Neon Slime', coins: 120, icon: '🧪', category: 'pranks' },

  // Category: NVIP
  { id: 'nvip-star', name: 'NVIP Star', coins: 999, icon: '⭐', category: 'nvip' },
  { id: 'nvip-falcon', name: 'Golden Falcon', coins: 1888, icon: '🦅', category: 'nvip' },
  { id: 'nvip-tiara', name: 'Diamond Tiara', coins: 2999, icon: '👑', category: 'nvip' },
  { id: 'nvip-carriage', name: 'Royal Carriage', coins: 6666, icon: '🛺', category: 'nvip' },
  { id: 'nvip-throne', name: 'Imperial Throne', coins: 8888, icon: '🪑', category: 'nvip' },
  { id: 'nvip-halo', name: 'Celestial Halo', coins: 5000, icon: '✨', category: 'nvip' },

  // Category: Celebrity
  { id: 'celeb-carpet', name: 'Red Carpet', coins: 888, icon: '🧧', category: 'celebrity' },
  { id: 'celeb-mic', name: 'Golden Mic', coins: 1288, icon: '🎙️', category: 'celebrity' },
  { id: 'celeb-flash', name: 'Paparazzi Flash', coins: 520, icon: '📸', category: 'celebrity' },
  { id: 'celeb-trophy', name: 'Grammy Trophy', coins: 3333, icon: '🏆', category: 'celebrity' },
  { id: 'celeb-limo', name: 'VIP Limousine', coins: 4500, icon: '🚘', category: 'celebrity' },
  { id: 'celeb-champagne', name: 'Dom Pérignon', coins: 1800, icon: '🍾', category: 'celebrity' },
];

export const RECHARGE_TIERS: RechargeTier[] = [
  { id: 'tier-140', coins: 140, bonusCoins: 2, priceUsd: 1.99 },
  { id: 'tier-500', coins: 500, bonusCoins: 64, priceUsd: 6.99 },
  { id: 'tier-700', coins: 700, bonusCoins: 118, priceUsd: 9.99, popular: true },
  { id: 'tier-1400', coins: 1400, bonusCoins: 280, priceUsd: 19.99 },
  { id: 'tier-3500', coins: 3500, bonusCoins: 850, priceUsd: 49.99 },
  { id: 'tier-7000', coins: 7000, bonusCoins: 2100, priceUsd: 99.99 },
];
