import { LiveMeStreamer, LiveMeGiftItem, RechargeTier } from './types';

export const LIVEME_STREAMERS: LiveMeStreamer[] = [
  {
    id: 'liveme-jasmine-54877736',
    handle: 'jasmine_live',
    name: 'Jasmine 💘',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500',
    isVerified: true,
    category: 'Vibes & Chat',
    title: 'Come chat and chill! 💘 Music & Good Vibes',
    description: 'Welcome to the room! Tap screen for hearts ♥ and drop a follow!',
    viewersCount: 50,
    totalViews: '1.5K',
    popularity: '1.9K',
    diamonds: 2386814,
    likesCount: 18450,
    videoStreamUrl: 'https://assets.mixkit.co/videos/preview/mixkit-fashion-model-in-neon-lighting-39878-large.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=900',
    tags: ['Music', 'Chill', 'Vibes'],
    topContributors: [
      { id: 'c1', name: 'ShadowWolf', avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120', rank: 1, contribution: 85400 },
      { id: 'c2', name: 'AngelEyes', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120', rank: 2, contribution: 42300 },
      { id: 'c3', name: 'ApexLegend', avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120', rank: 3, contribution: 29100 },
    ],
  },
  {
    id: 'liveme-minibae-1002',
    handle: 'minibae_official',
    name: 'MiniBae 💙',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500',
    isVerified: true,
    category: 'Gamer & Chill',
    title: '10k 👓 🫶 Good vibes only!',
    description: 'Gaming lounge and late night music requests.',
    viewersCount: 474,
    totalViews: '2.1K',
    popularity: '2.4K',
    diamonds: 1842100,
    likesCount: 24900,
    videoStreamUrl: 'https://assets.mixkit.co/videos/preview/mixkit-girl-in-a-neon-room-listening-to-music-40763-large.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=900',
    tags: ['Gaming', 'LoFi', 'LateNight'],
    topContributors: [
      { id: 'c4', name: 'CyberKnight', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120', rank: 1, contribution: 64000 },
      { id: 'c5', name: 'NeonPulse', avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120', rank: 2, contribution: 38500 },
      { id: 'c6', name: 'StarryNight', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120', rank: 3, contribution: 19200 },
    ],
  },
  {
    id: 'liveme-elena-1003',
    handle: 'elena_rodriguez',
    name: 'Elena Rodriguez',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=500',
    isVerified: true,
    category: 'Electronic DJ',
    title: 'Live Battle & Electro Beats Arena ⚡',
    description: 'Club mix live from Madrid. Drop hearts and help win the PK battle!',
    viewersCount: 1840,
    totalViews: '4.2K',
    popularity: '5.1K',
    diamonds: 3120450,
    likesCount: 68400,
    videoStreamUrl: 'https://assets.mixkit.co/videos/preview/mixkit-dj-mixing-music-in-a-club-41712-large.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=900',
    tags: ['DJ', 'Electronic', 'PKBattle'],
    topContributors: [
      { id: 'c7', name: 'Luciano', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120', rank: 1, contribution: 120500 },
      { id: 'c8', name: 'BeatDrop', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120', rank: 2, contribution: 74200 },
      { id: 'c9', name: 'Solaris', avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120', rank: 3, contribution: 45000 },
    ],
  },
  {
    id: 'liveme-5kjesss-1004',
    handle: '5kjesss',
    name: '☁️ 5KJesss 🧃',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=500',
    isVerified: false,
    category: 'Lifestyle',
    title: 'Soy de Canela y fuego ❤️‍🔥 Global Show',
    description: 'Charlando con amigos de todo el mundo. ¡Bienvenidos!',
    viewersCount: 687,
    totalViews: '687',
    popularity: '2.6K',
    diamonds: 1420000,
    likesCount: 15300,
    videoStreamUrl: 'https://assets.mixkit.co/videos/preview/mixkit-young-woman-talking-to-the-camera-42866-large.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=900',
    tags: ['Global', 'Charla', 'Musica'],
    topContributors: [
      { id: 'c10', name: 'MaxLondon', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120', rank: 1, contribution: 41000 },
      { id: 'c11', name: 'Sarita', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120', rank: 2, contribution: 29800 },
      { id: 'c12', name: 'KhattakPk', avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120', rank: 3, contribution: 18400 },
    ],
  },
  {
    id: 'liveme-julian-1005',
    handle: 'julian_analogue',
    name: 'Julian Thorne',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500',
    isVerified: true,
    category: 'Synthesizers',
    title: 'Analog Synth Session & Sound Design 🎹',
    description: 'Eurorack modular patches, deep sub frequencies and spatial reverb.',
    viewersCount: 340,
    totalViews: '1.1K',
    popularity: '1.5K',
    diamonds: 980500,
    likesCount: 11200,
    videoStreamUrl: 'https://assets.mixkit.co/videos/preview/mixkit-young-man-talking-on-a-video-call-42996-large.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=900',
    tags: ['Synthesizer', 'Eurorack', 'SoundLab'],
    topContributors: [
      { id: 'c13', name: 'FilterSweep', avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120', rank: 1, contribution: 31000 },
      { id: 'c14', name: 'Oscillator', avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120', rank: 2, contribution: 22000 },
      { id: 'c15', name: 'VCO', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120', rank: 3, contribution: 14000 },
    ],
  },
];

export const LIVEME_GIFTS: LiveMeGiftItem[] = [
  // Category: Popular (Exact LiveMe 4x4 Grid from Screenshot media_1790808554560.png)
  { id: 'crown-heart', name: 'Crown Heart', coins: 1, icon: '👑❤️', category: 'popular' },
  { id: 'rose', name: 'Rose', coins: 1, icon: '🌹', category: 'popular', isAnimation: true, animationKey: 'rose' },
  { id: 'bouquet', name: 'Bouquet', coins: 1, icon: '💐', category: 'popular' },
  { id: 'lightning', name: 'Lightning', coins: 1, icon: '⚡', category: 'popular' },
  { id: 'thumbs-up', name: 'Thumbs Up', coins: 1, icon: '👍', category: 'popular' },
  { id: 'cute-heart', name: 'Cute Heart', coins: 5, icon: '🥰', category: 'popular' },
  { id: 'high-heels', name: 'High Heels', coins: 5, icon: '👠', category: 'popular' },
  { id: 'taxi', name: 'Yellow Taxi', coins: 5, icon: '🚕', category: 'popular' },
  { id: 'red-lips', name: 'Red Lips', coins: 30, icon: '💋', category: 'popular' },
  { id: 'rainbow', name: 'Rainbow', coins: 30, icon: '🌈', category: 'popular' },
  { id: 'feather-duster', name: 'Feather Duster', coins: 69, icon: '🪶', category: 'popular' },
  { id: 'cocktail', name: 'Cocktail', coins: 99, icon: '🍹', category: 'popular' },
  { id: 'diamond-ring', name: 'Diamond Ring', coins: 520, icon: '💍', category: 'popular' },
  { id: 'kitten', name: 'Kitten', coins: 100, icon: '🐱', category: 'popular' },
  { id: 'angel', name: 'Angel Statue', coins: 500, icon: '👼', category: 'popular' },
  { id: 'magic-stamp', name: 'Magic Stamp', coins: 100, icon: '💮', category: 'popular' },

  // Category: Special
  { id: 'tropical-mosquito', name: 'Tropical Mosquito', coins: 69, icon: '🦟', category: 'special', isAnimation: true, animationKey: 'tropical-mosquito' },
  { id: 'dragon', name: 'Dragon', coins: 1314, icon: '🐉', category: 'special', isAnimation: true, animationKey: 'dragon' },
  { id: 'super-galaxy', name: 'Super Galaxy', coins: 3000, icon: '🌌', category: 'special', isAnimation: true, animationKey: 'super-galaxy' },
  { id: 'fireworks', name: 'Fireworks', coins: 299, icon: '🎆', category: 'special' },
  { id: 'luxury-yacht', name: 'Luxury Yacht', coins: 1999, icon: '🛥️', category: 'special' },
  { id: 'private-jet', name: 'Private Jet', coins: 4999, icon: '✈️', category: 'special' },
  { id: 'fairy-castle', name: 'Fairy Castle', coins: 9999, icon: '🏰', category: 'special' },
  { id: 'phoenix', name: 'Golden Phoenix', coins: 5200, icon: '🦅', category: 'special' },

  // Category: Pranks
  { id: 'prank-duster', name: 'Feather Tickle', coins: 69, icon: '🪶', category: 'pranks' },
  { id: 'prank-tomato', name: 'Rotten Tomato', coins: 10, icon: '🍅', category: 'pranks' },
  { id: 'prank-water', name: 'Water Splash', coins: 25, icon: '💦', category: 'pranks' },
  { id: 'prank-bomb', name: 'Stink Bomb', coins: 50, icon: '💣', category: 'pranks' },
  { id: 'prank-ghost', name: 'Ghost Pop', coins: 99, icon: '👻', category: 'pranks' },
  { id: 'prank-bucket', name: 'Ice Bucket', coins: 150, icon: '🪣', category: 'pranks' },
  { id: 'prank-pie', name: 'Cream Pie', coins: 88, icon: '🥧', category: 'pranks' },
  { id: 'prank-slime', name: 'Neon Slime', coins: 120, icon: '🧪', category: 'pranks' },

  // Category: NVIP
  { id: 'nvip-star', name: 'NVIP Star', coins: 999, icon: '⭐', category: 'nvip' },
  { id: 'nvip-falcon', name: 'Golden Falcon', coins: 1888, icon: '🦅', category: 'nvip' },
  { id: 'nvip-tiara', name: 'Diamond Tiara', coins: 2999, icon: '👑', category: 'nvip' },
  { id: 'nvip-carriage', name: 'Royal Carriage', coins: 6666, icon: '🛺', category: 'nvip' },
  { id: 'nvip-throne', name: 'Imperial Throne', coins: 8888, icon: '🪑', category: 'nvip' },
  { id: 'nvip-halo', name: 'Celestial Halo', coins: 5000, icon: '✨', category: 'nvip' },

  // Category: Celebrity
  { id: 'celeb-carpet', name: 'Red Carpet', coins: 888, icon: '🧧', category: 'celebrity' },
  { id: 'celeb-mic', name: 'Golden Mic', coins: 1288, icon: '🎙️', category: 'celebrity' },
  { id: 'celeb-flash', name: 'Paparazzi Flash', coins: 520, icon: '📸', category: 'celebrity' },
  { id: 'celeb-trophy', name: 'Grammy Trophy', coins: 3333, icon: '🏆', category: 'celebrity' },
  { id: 'celeb-limo', name: 'VIP Limousine', coins: 4500, icon: '🚘', category: 'celebrity' },
  { id: 'celeb-champagne', name: 'Dom Pérignon', coins: 1800, icon: '🍾', category: 'celebrity' },
];

export const RECHARGE_TIERS: RechargeTier[] = [
  { id: 'tier-140', coins: 140, bonusCoins: 2, priceUsd: 1.99 },
  { id: 'tier-500', coins: 500, bonusCoins: 64, priceUsd: 6.99 },
  { id: 'tier-700', coins: 700, bonusCoins: 118, priceUsd: 9.99, popular: true },
  { id: 'tier-1400', coins: 1400, bonusCoins: 280, priceUsd: 19.99 },
  { id: 'tier-3500', coins: 3500, bonusCoins: 850, priceUsd: 49.99 },
  { id: 'tier-7000', coins: 7000, bonusCoins: 2100, priceUsd: 99.99 },
];
